version: '3.8'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - user-db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: MzNhZGNqMGFzZG1ha2xzbGRmbGtzYWRmbGtqYXNkbGZramFzZGZsazM0MjM0MzIzMTIzMTIzMTIzMTIzMTIzMTIzMTIzMTIzMTIz
      JWT_EXPIRATION: 3600000
    networks:
      - backend

  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - backend

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    depends_on:
      - product-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - backend
  purchase-service:
    build:
      context: ./purchase-service
    container_name: purchase-service
    depends_on:
      - user-service
      - product-service
    ports:
      - "8083:8083"
    networks:
      - backend

networks:
  backend:
